# Generated by Django 2.0.2 on 2018-02-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_field', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.SlugField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='1', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='slug',
            field=models.SlugField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='title',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
