# Generated by Django 2.0.2 on 2018-02-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_simple',
            field=models.BooleanField(default=True),
        ),
    ]
