# Generated by Django 2.0.2 on 2018-02-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parameter',
            field=models.ManyToManyField(blank=True, to='shop.Parameter'),
        ),
    ]
